esp32:
  board: esp32-s2-saola-1
  framework:
    type: arduino
    version: 2.0.3
    platform_version: 4.4.0

esphome:
  name: alarmbuddy


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "AlarmbuddyFallback"
    password: "alarmbuddy"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
binary_sensor:
  - platform: gpio
    name: "INPUT1"
    pin:
      number: 1
      inverted: True
      mode: INPUT_PULLDOWN
  
  - platform: gpio 
    name: "INPUT2"
    pin:
      number: 2
      inverted: True
      mode: INPUT_PULLDOWN
        
  - platform: gpio 
    name: "INPUT3"
    pin:
      number: 3
      inverted: True
      mode: INPUT_PULLDOWN
        
  - platform: gpio 
    name: "INPUT4"
    pin:
      number: 4
      inverted: True
      mode: INPUT_PULLDOWN
        
  - platform: gpio 
    name: "INPUT5"
    pin:
      number: 5
      inverted: True
      mode: INPUT_PULLDOWN
        
  - platform: gpio 
    name: "INPUT6"
    pin:
      number: 6
      inverted: True
      mode: INPUT_PULLDOWN
        
  - platform: gpio 
    name: "INPUT7"
    pin:
      number: 7
      inverted: True
      mode: INPUT_PULLDOWN
        
  - platform: gpio 
    name: "INPUT8"
    pin:
      number: 8
      inverted: True
      mode: INPUT_PULLDOWN
        
  - platform: gpio 
    name: "INPUT9"
    pin:
      number: 9
      inverted: True
      mode: INPUT_PULLDOWN
        
  - platform: gpio 
    name: "INPUT10"
    pin:
      number: 12
      inverted: True
      mode: INPUT_PULLDOWN

  - platform: gpio 
    name: "INPUT11"
    pin:
      number: 11
      inverted: True
      mode: INPUT_PULLDOWN

  - platform: gpio 
    name: "INPUT12"
    pin:
      number: 10
      inverted: True
      mode: INPUT_PULLDOWN