esphome:
  name: alarmbuddy
  platform: ESP32
  board: esp32dev

wifi:
  ssid: "yourssid"
  password: "yourwifi"

  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    ssid: "AlarmbuddyFallback"
    password: "alarmbuddy"

captive_portal:

# Enable logging
logger:

# Enable Home Assistant API
api:

ota:
binary_sensor:
  - platform: gpio
    name: "INPUT1"
    pin:
      number: 32
      inverted: True
      mode: INPUT_PULLDOWN
  
  - platform: gpio 
    name: "INPUT2"
    pin:
      number: 33
      inverted: True
      mode: INPUT_PULLDOWN
        
  - platform: gpio 
    name: "INPUT3"
    pin:
      number: 25
      inverted: True
      mode: INPUT_PULLDOWN
        
  - platform: gpio 
    name: "INPUT4"
    pin:
      number: 26
      inverted: True
      mode: INPUT_PULLDOWN
        
  - platform: gpio 
    name: "INPUT5"
    pin:
      number: 27
      inverted: True
      mode: INPUT_PULLDOWN
        
  - platform: gpio 
    name: "INPUT6"
    pin:
      number: 14
      inverted: True
      mode: INPUT_PULLDOWN
        
  - platform: gpio 
    name: "INPUT7"
    pin:
      number: 12
      inverted: True
      mode: INPUT_PULLDOWN
        
  - platform: gpio 
    name: "INPUT8"
    pin:
      number: 13
      inverted: True
      mode: INPUT_PULLDOWN
        
  - platform: gpio 
    name: "INPUT9"
    pin:
      number: 13
      inverted: True
      mode: INPUT_PULLDOWN
        
  - platform: gpio 
    name: "INPUT10"
    pin:
      number: 16
      inverted: True
      mode: INPUT_PULLDOWN